/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redes;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jacobo
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
           origen.setLineWrap(true);
        destino.setLineWrap(true);
        origen.setWrapStyleWord(true);
        destino.setWrapStyleWord(true);
    
        
      
      
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        origen = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        destino = new javax.swing.JTextArea();
        BtnTextBin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Ingrese Texto");

        origen.setColumns(20);
        origen.setRows(5);
        jScrollPane1.setViewportView(origen);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Resultado en binario");

        destino.setColumns(20);
        destino.setRows(5);
        jScrollPane2.setViewportView(destino);

        BtnTextBin.setText("Enviar ");
        BtnTextBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTextBinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnTextBin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(132, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(94, 304, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(BtnTextBin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTextBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTextBinActionPerformed
        String texto = origen.getText();
 
       
        
        //String texto = "";
        //char[] letra;
        //  char [] letra = texto.toCharArray();
        //String texto="puto";
        String codigoBinario = "";//guarda el en binario
        // char letra;
        int contadorerror =0;
        int tam = texto.length();
        

            String R= null;
            String e= null;
            String d= null;
            String s= null;
            if (texto.equals("Redes "))  {

                char ERRORES[] = new char[80];
                char palabrafrase[] = new char[80];
                ArrayList<String> cadenabinario = new ArrayList<String>();
                
          
                cadenabinario.add("00110001011011100011000101100011");
                for (int i = 0; i < texto.length(); i++)

                {
                      
                    //recorre el texto ingresado
                    char letra = texto.charAt(i);//separa letra a letra

                    if (palabrafrase[i]==letra)
                    {
                        ERRORES[i]='0';
                    }
                    else
                    {
                        
                        ERRORES[i]='1';
                        contadorerror++;
                        
                        
                    }
                    
                    int aux = Binario((int) (letra)).length();//almacena largo del binario de la letra devuelta
                    for (int j = 0; j < 8; j++) {//recorrido de 8 characteres
                        if (aux < 8) {//si el largo del binario es menor a 7 (0-7)entonces

                            codigoBinario = codigoBinario + "0";//agregar 0 a la concadenacion
                            aux++;
                            //System.out.println("la posiscion s " +j );
                            
                        }
                        

                    }
                    cadenabinario.add("0"+ Binario((int) (letra)));
                    codigoBinario = codigoBinario + Binario ((int) (letra))+" = "+ letra +" " + " - "  ;
                    if(contadorerror==0)
                        
                    {
                        
                        
                        
  
                        
                        jLabel9.setText("la frase es correcta ");
                        
                        
                        
                        
                        
                
                    }
                    
              
                
                            
                    
                       
               
                    
                    if(contadorerror>=1)
                    {
                        jLabel9.setText("la frase es incorrecta ");
                    }
                    //codigoBinario = codigoBinario + "g" ;
                }
              
                   cadenabinario.add("01000110001100010110111001100001");
                
                
                
                
        int n;
		
		ArrayList<String> arreglo = new ArrayList<String>();
                arreglo.add("1010010");
                arreglo.add("1100101");
                arreglo.add("1100100");
                arreglo.add("1100101");
                arreglo.add("1110011");
                arreglo.add("0100000");
                for(int j=0; j<arreglo.size(); j++)
                {
               int  ta = arreglo.get(j).length();
                int datas[] = new int[ta];
                char[] cadena = arreglo.get(j).toCharArray();
                int contador=0;
                for(char cad:cadena)
                {
                    datas[contador]=Character.getNumericValue(cad);
                    contador++;
                }
                
                
                  int divi[]=new int [5];
                divi[0]=1;
                 divi[1]=0;
                  divi[2]=1;
                   divi[3]=0;
                    divi[4]=1;
                    
                    
                   
                
                
                
        // Divide the inputted data by the inputted divisor
		// Store the remainder that is returned by the method
		int remainder[] = divide(datas, divi);
		for(int i=0 ; i < remainder.length-1 ; i++) {
			System.out.print(remainder[i]);
		}
		System.out.println("\nThe CRC code generated is:");
                //jLabel4.setText("el crc generado es  ");
		String crc2="";
		for(int i=0 ; i < datas.length ; i++) {
			System.out.print(datas[i]);
                        crc2= crc2+datas[i];
                         // jLabel5.setText(" "+crc2);
                        
		}
                String crc3="";
		for(int i=0 ; i < remainder.length-1 ; i++) {
                    crc3=crc3+remainder[i];
			System.out.print(remainder[i]);
                         // jLabel6.setText(" "+crc3);
                        // jLabel4.setText("Error en la posicion "+" "+x+" "+"La letra deveria ser "+" "+palabrafrase[x]);
		}
		System.out.println();
                int contador1=0;
                    jLabel3.setText("el crc generado es  "+crc2+crc3 );
                  jLabel4.setText("el crc generado es  "+crc2+crc3 );
                }
                
                
                
                
                
                String conca="";
                String fori="";
                for (int x =0; x<texto.length(); x++)
                {
                    if(ERRORES[x] == '1')
                    {
                        fori=fori+x+",";
                        conca=conca+palabrafrase[x]+",";
                        // jLabel4.setText("Error en la posicion "+" "+x+" "+"La letra deveria ser "+" "+palabrafrase[x]);
                        jLabel9.setText("Error en la posicion "+" "+fori+""+"La letra deveria ser "+""+conca+"");

                        //System.out.println("ERROR EN LA POSICION "+x+" LA LETRA DEBERIA DE SER "+palabrafrase[x]);
                    }
                    //jLabel4.setText(conca);

                }
                
                   destino.setText(codigoBinario);/*imprime el codigo binario completo*/
        destino.append("\n Cadena completa: ");
        for(int x=0; x<cadenabinario.size();x++)
                {
                    destino.append("\n"+cadenabinario.get(x));
                }
            }
            
            
            
                //}  //  FIN DE IF COMPROBACION
            //FIN DE IF DE TAM==&
        if(tam <=5)
        {

            for (int i = 0; i < texto.length(); i++)

            {

                //recorre el texto ingresado
                char letra = texto.charAt(i);//separa letra a letra

                int aux = Binario((int) (letra)).length();//almacena largo del binario d ela letra devuelta
                for (int j = 0; j < 8; j++) {//recorrido de 8 characteres
                    if (aux < 8) {//si el largo del binario es menor a 7 (0-7)entonces

                        codigoBinario = codigoBinario + "0";//agregar 0 a la concadenacion
                        aux++;
                        //System.out.println("la posiscion s " +j );

                    }

                }

                codigoBinario = codigoBinario + Binario ((int) (letra))+" = "+ letra +" " + " ; "  ;
                //  jLabel4.setText("la frase es correcta ");
                //codigoBinario = codigoBinario + "g" ;

            }

            jLabel9.setText("Error la frase es muy corta");
        }

        else if(tam >=7)
        {

            for (int i = 0; i < texto.length(); i++)

            {

                //recorre el texto ingresado
                char letra = texto.charAt(i);//separa letra a letra

                int aux = Binario((int) (letra)).length();//almacena largo del binario d ela letra devuelta
                for (int j = 0; j < 8; j++) {//recorrido de 8 characteres
                    if (aux < 8) {//si el largo del binario es menor a 7 (0-7)entonces

                        codigoBinario = codigoBinario + "0";//agregar 0 a la concadenacion
                        aux++;
                        //System.out.println("la posiscion s " +j );

                    }

                }

                codigoBinario = codigoBinario + Binario ((int) (letra))+" = "+ letra +" " + " ; "  ;
                //  jLabel4.setText("la frase es correcta ");
                //codigoBinario = codigoBinario + "g" ;

            }

            jLabel9.setText(" error la frase es muy larga ");
        }

     
        
    }//GEN-LAST:event_BtnTextBinActionPerformed
    
    
    
    
    
       static int[] divide(int old_data[], int divisor[]) {
		int remainder[] , i;
		int data[] = new int[old_data.length + divisor.length];
		System.arraycopy(old_data, 0, data, 0, old_data.length);
		// Remainder array stores the remainder
		remainder = new int[divisor.length];
		// Initially, remainder's bits will be set to the data bits
		System.arraycopy(data, 0, remainder, 0, divisor.length);
		
		// Loop runs for same number of times as number of bits of data
		// This loop will continuously exor the bits of the remainder and
		// divisor
		for(i=0 ; i < old_data.length ; i++) {
			System.out.println((i+1) + ".) First data bit is : "
								+ remainder[0]);
			System.out.print("Remainder : ");
			if(remainder[0] == 1) {
				// We have to exor the remainder bits with divisor bits
				for(int j=1 ; j < divisor.length ; j++) {
					remainder[j-1] = exor(remainder[j], divisor[j]);
					System.out.print(remainder[j-1]);
				}
			}
			else {
				// We have to exor the remainder bits with 0
				for(int j=1 ; j < divisor.length ; j++) {
					remainder[j-1] = exor(remainder[j], 0);
					System.out.print(remainder[j-1]);
				}
			}
			// The last bit of the remainder will be taken from the data
			// This is the 'carry' taken from the dividend after every step
			// of division
			remainder[divisor.length-1] = data[i+divisor.length];
			System.out.println(remainder[divisor.length-1]);
		}
		return remainder;
	}
	
	static int exor(int a, int b) {
		// This simple function returns the exor of two bits
		if(a == b) {
			return 0;
		}
		return 1;
	}
    
    
    
    
      static int[] divide(int dividendo[],int largo_p[], int resto[])
     {
        int contador=0;
        while(true)
        {
            for(int i=0;i<largo_p.length;i++)
                resto[contador+i]=(resto[contador+i]^largo_p[i]);
            
            while(resto[contador]==0 && contador!=resto.length-1)
                contador++;
    
            if((resto.length-contador)<largo_p.length)
                break;
        }
       
        return resto;
     
        
    }
    
    
    
    
    
    
       private String Binario(int Decimal) {
        int R, x = 0;//variables que se implementaran
        String Binario = ""; //guarda el contenido en codigo binario
        R = Decimal % 2;//resto del parametro 
        if (R == 1) {//si el resto es 1
            while (Decimal > 1) {//si el parametro es mas grande q el resto
                Decimal /= 2;//entonces decimal se divide en 2 y se guarda en decimal
                x = Decimal % 2;//x contendra el resto del decimal
                Binario = String.valueOf(x + Binario);//binario se ira formando de forma correcta y no alreves
            }
        } else {//si resto no es 1
            while (Decimal > 0) {//y decimal es mayor a 0
                Decimal /= 2;//decimal se divide en 2
                x = Decimal % 2;//x contendra el resto del decimal resultante
                Binario = String.valueOf(x + Binario);//se forma el numero en binario de forma correcta
            }
        }
        return String.valueOf(Binario + x);//devuelve el binario resultante mas el ultimo bit
    }

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTextBin;
    private javax.swing.JTextArea destino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea origen;
    // End of variables declaration//GEN-END:variables
}
